#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# Regenerate template/assets/{css/bundles,js}/*.{css,js} from source partials.
# Run after editing any file this script reads. Bundling is pure
# concatenation (order matters — mirrors the cascade order ThemeHook.php
# used to enqueue individually), followed by minification of the final
# output only (sources stay untouched/human-readable). No npm/build-tool
# RUNTIME dependency is introduced — this still runs as a one-file shell
# script, dev-machine-only, before the plain static files get committed.
#
# CSS minification: scripts/minify-css.py, a hand-rolled whitespace/comment
# stripper — NOT lightningcss/esbuild/bun's CSS engine. Tried those first;
# lightningcss 1.0.0-alpha.72 rewrites `:not(.x)::before` into two
# selectors, one missing the pseudo-element entirely (a real semantic bug,
# confirmed on this codebase's own core.css). The hand-rolled minifier only
# ever removes comments and insignificant whitespace — it does not parse or
# rewrite a single selector/rule, so it cannot introduce that class of bug.
# Gets ~10-33% off raw bytes here (most of the codebase is already written
# comment-heavy but declaration-dense, so gains come from stripped Vietnamese
# explanatory comments + blank lines, not "smart" restructuring).
#
# JS minification: `bun build --minify` (real AST-aware minifier — safe for
# JS, unlike lightningcss's CSS-specific bug above; JS minifiers from
# esbuild/bun are a much more mature, battle-tested code path).
# ──────────────────────────────────────────────────────────────
# Grouping rationale (see ThemeHook::enqueue_common_css_assets()):
# - core: always render-blocking on every page (tokens + chrome + mobile).
#   mobile.css is NOT a per-template defer candidate — it hides
#   .nh-header__call (visible by default) at <=760px; deferring it would
#   flash the header broken. Always bundle it with core.
# - deferred-base: always non-blocking on every page (search + forms —
#   neither is ever needed for first paint, see their own file comments).
# - blocking-{a,b,c,d} / deferred-{a,b,c,d}: the 6 files whose above-fold
#   need was measured per template with Playwright (see git log). Templates
#   sharing an identical blocking/deferred split share a group letter.
#     a = about, art, space, taste
#     b = network, original
#     c = front-page
#     d = contact
#     default = any singular/archive not covered above (blog index, category,
#       taxonomy, single-post, single-project/portfolio/event) — safe
#       fallback: everything render-blocking, nothing deferred (correct,
#       just not minimal; extend the Playwright analysis to add a group).
# ──────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CSS="$SCRIPT_DIR/../template/assets/css"
OUT="$CSS/bundles"
mkdir -p "$OUT"

bundle() {
    local out="$OUT/$1"; shift
    {
        echo "/* Generated by scripts/build-css-bundles.sh — do not hand-edit. Edit the source files below and re-run. */"
        for f in "$@"; do
            local src="$CSS/$f"
            [ -f "$src" ] || src="$SCRIPT_DIR/../$f"
            echo ""
            echo "/* ── source: $f ── */"
            cat "$src"
        done
    } > "$out"
    local raw_bytes
    raw_bytes=$(wc -c < "$out")
    python3 "$SCRIPT_DIR/minify-css.py" "$out" "$out"
    echo "wrote $out ($raw_bytes -> $(wc -c < "$out") bytes minified)"
}

# child-theme.css (wp-content/themes/underscores-child/assets/css/child-theme.css) used
# to be its own render-blocking <link> — the theme's REQUIRED style.css header lives at
# the theme root and is never enqueued; this one holds real always-blocking CSS (single-
# content layout, about-page timeline/team tweaks, partner grid, site-wide CF7 newsletter
# overrides) that was simply never folded into the bundle pipeline. It has zero above/
# below-fold split of its own (always loaded render-blocking on every page already), so
# folding it into core.css (also always render-blocking, always loaded) is a same-priority
# merge — cuts 1 request with no change to paint timing. Checked for selector collisions
# against the other partials: the only overlaps (.section-timeline .nh-intro__title/__lead,
# [data-page="about"] .section-intro .nh-intro__lead) share identical property values on
# both sides, so cascade-order effects are inert either way.
bundle core.css \
    tokens/colors.css tokens/typography.css tokens/layout.css \
    tokens/figma-variables.css tokens/base.css chrome.css mobile.css \
    wp-content/themes/underscores-child/assets/css/child-theme.css

bundle deferred-base.css search.css forms.css

bundle blocking-a.css content.css media.css pages.css
bundle deferred-a.css actions.css home-sections.css utilities.css

bundle blocking-b.css content.css media.css pages.css utilities.css
bundle deferred-b.css actions.css home-sections.css

bundle blocking-c.css actions.css content.css media.css
bundle deferred-c.css home-sections.css pages.css utilities.css

bundle blocking-d.css media.css pages.css
bundle deferred-d.css actions.css content.css home-sections.css utilities.css

bundle blocking-default.css \
    actions.css content.css home-sections.css media.css pages.css utilities.css


# ── JS: nhato-icons.js (156KB, SVG sprite + MutationObserver re-injector)
# always loads before nhato.js (UI behaviour) — same dependency ThemeHook.php
# used to declare via wp_enqueue_script 'deps'. Both are self-contained IIFEs
# `(function(){...})()`, so concatenating in this order preserves both the
# load-order guarantee and each file's own scope (no global leakage/clash).
# Minified with `bun build` (see header comment for why not for CSS too).
JS="$SCRIPT_DIR/../template/assets"
JS_TMPDIR="$(mktemp -d)"
trap 'rm -rf "$JS_TMPDIR"' EXIT
JS_RAW="$JS_TMPDIR/bundle.raw.js"
{
    echo "/* Generated by scripts/build-css-bundles.sh — do not hand-edit. Edit the source files below and re-run. */"
    echo ""
    echo "/* ── source: icons/nhato-icons.js ── */"
    cat "$JS/icons/nhato-icons.js"
    echo ""
    echo "/* ── source: js/nhato.js ── */"
    cat "$JS/js/nhato.js"
} > "$JS_RAW"
raw_js_bytes=$(wc -c < "$JS_RAW")
command -v bun >/dev/null 2>&1 || { echo "error: bun not found — required to minify template/assets/js/bundle.js (dev-machine-only build step, not a site runtime dependency)" >&2; exit 1; }
bun build "$JS_RAW" --minify --outfile="$JS/js/bundle.js" >/dev/null
echo "wrote $JS/js/bundle.js ($raw_js_bytes -> $(wc -c < "$JS/js/bundle.js") bytes minified)"
echo "Done."

