<?php
declare(strict_types=1);
defined('ABSPATH') || exit;

$page_fields = function_exists('get_fields') ? (get_fields() ?: []) : [];
$_page_sections = [
    'banner' => is_array($page_fields['banner_settings'] ?? null) ? $page_fields['banner_settings'] : [],
    'intro' => is_array($page_fields['intro_settings'] ?? null) ? $page_fields['intro_settings'] : [],
    'timeline' => is_array($page_fields['timeline_settings'] ?? null) ? $page_fields['timeline_settings'] : [],
    'values' => is_array($page_fields['values_settings'] ?? null) ? $page_fields['values_settings'] : [],
    'team' => is_array($page_fields['team_settings'] ?? null) ? $page_fields['team_settings'] : [],
    'videos' => is_array($page_fields['videos_settings'] ?? null) ? $page_fields['videos_settings'] : [],
];
$section_enabled = 'underscores_child_section_is_visible';
$banner_settings = $_page_sections['banner'];
$intro_settings = $_page_sections['intro'];
$timeline_settings = $_page_sections['timeline'];
$values_settings = $_page_sections['values'];
$team_settings = $_page_sections['team'];
$videos_settings = $_page_sections['videos'];

// Expected ACF sections: banner_settings, intro_settings, timeline_settings,
// values_settings, team_settings, videos_settings.
$image_url = 'underscores_child_acf_image_url';
$hero_image = $image_url($banner_settings['image'] ?? get_post_thumbnail_id());
$hero_lead = (string) ($banner_settings['lead'] ?? '');
if ($section_enabled($banner_settings) && ($hero_image !== '' || $hero_lead !== '' || get_the_title() !== '')) : ?><section class="nh-hero nh-hero--section"><?php if ($hero_image !== '') : ?><div class="nh-hero__media"><img src="<?php echo esc_url($hero_image); ?>" alt="" fetchpriority="high"></div><?php endif; ?><div class="nh-hero__overlay"></div><div class="nh-hero__inner nh-container"><?php if (get_the_title() !== '') : ?><h1 class="nh-hero__title"><?php the_title(); ?></h1><?php endif; ?><?php if ($hero_lead !== '') : ?><p class="nh-hero__lead"><?php echo esc_html($hero_lead); ?></p><?php endif; ?></div></section><?php endif;

$intro_title = (string) ($intro_settings['title'] ?? '');
$intro_lead = (string) ($intro_settings['lead'] ?? '');
$intro_wide = $image_url($intro_settings['image'] ?? '');
$intro_images = is_array($intro_settings['images'] ?? null) ? $intro_settings['images'] : [];
if ($section_enabled($intro_settings) && ($intro_title !== '' || $intro_lead !== '' || $intro_wide !== '' || $intro_images !== [])) : ?><section class="section-intro"><div class="nh-container nh-stack"><div class="nh-intro"><?php if ($intro_title !== '') : ?><h2 class="nh-intro__title"><?php echo wp_kses_post($intro_title); ?></h2><?php endif; ?><?php if ($intro_lead !== '') : ?><p class="nh-intro__lead"><?php echo esc_html($intro_lead); ?></p><?php endif; ?></div><?php if ($intro_wide !== '') : ?><img src="<?php echo esc_url($intro_wide); ?>" alt="" class="nh-intro__wide-image" loading="lazy"><?php endif; ?><?php if ($intro_images !== []) : ?><div class="nh-grid-2 u-gap-40"><?php foreach ($intro_images as $image) : $src = $image_url($image); if ($src !== '') : ?><img src="<?php echo esc_url($src); ?>" alt="" class="nh-intro__grid-image" loading="lazy"><?php endif; endforeach; ?></div><?php endif; ?></div></section><?php endif;

$timeline = is_array($timeline_settings['items'] ?? null) ? $timeline_settings['items'] : [];
if ($section_enabled($timeline_settings) && $timeline !== []) : ?><section class="section-timeline"><div class="nh-container nh-stack"><div class="nh-intro"><?php if (!empty($timeline_settings['eyebrow'])) : ?><p class="nh-flanked"><span><?php echo wp_kses_post((string) $timeline_settings['eyebrow']); ?></span></p><?php endif; ?><?php if (!empty($timeline_settings['title'])) : ?><h2 class="nh-intro__title"><?php echo wp_kses_post((string) $timeline_settings['title']); ?></h2><?php endif; ?><?php if (!empty($timeline_settings['lead'])) : ?><p class="nh-intro__lead"><?php echo esc_html((string) $timeline_settings['lead']); ?></p><?php endif; ?></div><div class="nh-grid-4"><?php foreach ($timeline as $index => $step) : if (!is_array($step)) { continue; } $src = $image_url($step['image'] ?? ''); ?><article class="nh-step-card"><?php if ($src !== '') : ?><span class="nh-step-card__image"><img src="<?php echo esc_url($src); ?>" alt="" loading="lazy"></span><?php endif; ?><span class="nh-step-card__body"><span class="nh-step-card__num"><em><?php echo esc_html((string) ($step['number'] ?? sprintf('%02d', $index + 1))); ?></em><i></i></span><?php if (!empty($step['title'])) : ?><span class="nh-step-card__title"><?php echo esc_html((string) $step['title']); ?></span><?php endif; ?><?php if (!empty($step['text'])) : ?><span class="nh-step-card__text"><?php echo esc_html((string) $step['text']); ?></span><?php endif; ?></span></article><?php endforeach; ?></div></div></section><?php endif;

$vision = is_array($values_settings['vision'] ?? null) ? $values_settings['vision'] : [];
$mission = is_array($values_settings['mission'] ?? null) ? $values_settings['mission'] : [];
$values = is_array($values_settings['items'] ?? null) ? $values_settings['items'] : [];
if ($section_enabled($values_settings) && ($vision !== [] || $mission !== [] || $values !== [])) : ?><section class="section-values"><div class="nh-container nh-stack"><div class="nh-grid-2"><?php foreach ([$vision, $mission] as $card) : if ($card === []) { continue; } $src = $image_url($card['image'] ?? ''); $card_icon_id = absint($card['icon'] ?? 0); ?><div class="nh-mission"<?php if ($src !== '') : ?> style="--nh-mission-image:url('<?php echo esc_url($src); ?>')"<?php endif; ?>><?php if ($card_icon_id > 0) : ?><span class="nh-mission__icon"><?php echo wp_get_attachment_image($card_icon_id, 'thumbnail', false, ['alt' => '', 'loading' => 'lazy']); ?></span><?php endif; ?><?php if (!empty($card['title'])) : ?><h2 class="nh-mission__title"><?php echo esc_html((string) $card['title']); ?></h2><?php endif; ?><?php if (!empty($card['text'])) : ?><p class="nh-mission__text"><?php echo esc_html((string) $card['text']); ?></p><?php endif; ?></div><?php endforeach; ?></div><?php if ($values !== []) : ?><div class="nh-values-head"><?php if (!empty($values_settings['eyebrow'])) : ?><p class="nh-eyebrow"><?php echo esc_html((string) $values_settings['eyebrow']); ?></p><?php endif; ?><?php if (!empty($values_settings['title'])) : ?><h2 class="nh-intro__title"><?php echo esc_html((string) $values_settings['title']); ?></h2><?php endif; ?></div><div class="nh-values"><?php foreach ($values as $value) : if (!is_array($value)) { continue; } ?><div class="nh-value"><?php if (!empty($value['title'])) : ?><strong><?php echo esc_html((string) $value['title']); ?></strong><?php endif; ?><?php if (!empty($value['text'])) : ?><p><?php echo esc_html((string) $value['text']); ?></p><?php endif; ?></div><?php endforeach; ?></div><?php endif; ?></div></section><?php endif;

$team = is_array($team_settings['items'] ?? null) ? $team_settings['items'] : [];
if ($section_enabled($team_settings) && $team !== []) : ?><section class="section-team"><div class="nh-container section-team__inner"><div class="nh-intro"><?php if (!empty($team_settings['eyebrow'])) : ?><p class="nh-intro__eyebrow"><?php echo esc_html((string) $team_settings['eyebrow']); ?></p><?php endif; ?><?php if (!empty($team_settings['title'])) : ?><h2 class="nh-section-title"><?php echo esc_html((string) $team_settings['title']); ?></h2><?php endif; ?></div><div class="nh-team-slider" data-nh-slider><div class="nh-team-slider__track" data-nh-slider-track><?php foreach ($team as $member) : if (!is_array($member)) { continue; } $photo = $member['photo_id'] ?? $member['photo'] ?? $member['image'] ?? 0; $photo_id = is_array($photo) ? absint($photo['ID'] ?? $photo['id'] ?? 0) : absint($photo); get_template_part('partials/components/card-team', null, ['name' => $member['name'] ?? $member['title'] ?? '', 'role' => $member['role'] ?? $member['job_title'] ?? '', 'photo_id' => $photo_id]); endforeach; ?></div><button class="nh-carousel-arrow nh-team-slider__prev" type="button" data-nh-slider-prev aria-label="<?php esc_attr_e('Trước', 'underscores-child'); ?>"><?php echo underscores_child_icon_mask('icon_carousel_left'); ?></button><button class="nh-carousel-arrow nh-team-slider__next" type="button" data-nh-slider-next aria-label="<?php esc_attr_e('Sau', 'underscores-child'); ?>"><?php echo underscores_child_icon_mask('icon_carousel_right'); ?></button></div></div></section><?php endif;

$videos = is_array($videos_settings['items'] ?? null) ? $videos_settings['items'] : [];
if ($section_enabled($videos_settings) && $videos !== []) : ?><section class="section-video"><div class="nh-container nh-stack"><div class="nh-video-head"><?php if (!empty($videos_settings['eyebrow'])) : ?><p class="nh-eyebrow"><?php echo esc_html((string) $videos_settings['eyebrow']); ?></p><?php endif; ?><?php if (!empty($videos_settings['title'])) : ?><h2 class="nh-section-title"><?php echo esc_html((string) $videos_settings['title']); ?></h2><?php endif; ?></div><div class="nh-grid-4"><?php foreach ($videos as $video) : if (!is_array($video)) { continue; } $thumbnail = $video['thumbnail_id'] ?? $video['thumbnail'] ?? $video['image'] ?? 0; $thumbnail_id = is_array($thumbnail) ? absint($thumbnail['ID'] ?? $thumbnail['id'] ?? 0) : absint($thumbnail); get_template_part('partials/components/card-video', null, ['youtube_url' => $video['youtube_url'] ?? $video['url'] ?? '', 'thumbnail_id' => $thumbnail_id, 'title' => $video['title'] ?? '', 'variant' => 'about']); endforeach; ?></div><?php $videos_cta = is_array($videos_settings['cta'] ?? null) ? $videos_settings['cta'] : []; if (!empty($videos_cta['url']) && !empty($videos_cta['title'])) : ?><a class="nh-cta nh-cta--ink" href="<?php echo esc_url((string) $videos_cta['url']); ?>"<?php if (!empty($videos_cta['target'])) : ?> target="<?php echo esc_attr((string) $videos_cta['target']); ?>"<?php endif; ?>><?php echo esc_html((string) $videos_cta['title']); ?><span class="nh-cta__arrow"><?php echo underscores_child_icon_mask('icon_arrow_right'); ?></span></a><?php endif; ?></div></section><?php endif;
